# Generated by Django 4.0.3 on 2022-03-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Fast_name',
            new_name='Fast_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='Last_Name',
        ),
    ]
